[package]
name = "grpc-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { version = "1.37", features = ["full"] }
tokio-stream = "0.1.15"

[build-dependencies]
tonic-build = "0.11"
